name: PHP Composer

on:
  push:
    branches: [ master, v1.1, build-test ]
  schedule:
    - cron:  '5 15 1,31 * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: build api files
        run: composer build

      - name: commit and push
        env:
          TZ: 'Asia/Tokyo'
        run: |
          git add -N .
          if ! git diff --exit-code --quiet
          then
            git config user.email "matsuoshi@gmail.com"
            git config user.name "from GitHub Actions"
            git add --all
            git commit -m "$(date +'%Y-%m-%d %H:%M:%S')"
            git push
          fi
