name: touch

on:
  schedule:
    - cron:  '0 3 1 * *'
  workflow_dispatch:

jobs:
  touch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: touch

      - name: touch
        env:
          TZ: 'Asia/Tokyo'
        run: date '+%F %T' > touch.txt

      - name: commit and push
        run: |
          git config user.email "matsuoshi@gmail.com"
          git config user.name "from GitHub Actions"
          git add --all
          git commit -m "touch"
          git push
